### ISSUE TITLE
Only first group of node types is displayed in Cheat Sheet when using firefox

### ISSUE THREAD

**Issue by otaviobp** [solettaproject/soletta-dev-app#76] opened 2016-04-11 20:58 UTC
When using firefox browser, the Cheat Sheet only display first group of node types. In chrome web browser it works fine.
Tested with soletta-dev-app beta17

![screenshot_20160411_175737](https://cloud.githubusercontent.com/assets/36560/14442231/f438dbc4-000e-11e6-8bd9-5614e59c4308.png)

**Comment by bdilly** [comment] 2016-04-11 21:02
I'm using Firefox 45.0 and it seems to be working fine

**Comment by bdilly** [comment] 2016-04-11 21:03
I'm checking it against our online version (not beta17) - http://solettaproject.github.io/docs/nodetypes/

**Comment by otaviobp** [comment] 2016-04-11 21:39
The online version is working fine here too (using firefox 45.0.1).
Tested with dev-app on master and it is also failing.

**Comment by brunobottazzini** [comment] 2016-04-11 23:18
Yes I can confirm this bug.

When looking in the console errors the firefox points to me for this:
https://github.com/desandro/get-size/#firefox-hidden-iframe-bug

It is a conflict between angularjs and firefox. The angular uses the "display: none". 

I will go through this bug

**Comment by brunobottazzini** [comment] 2016-05-09 17:34
@bdilly, @otaviobp proposed fix here: https://github.com/solettaproject/soletta-dev-app/pull/100

Can you guys test/review it ?

**Comment by otaviobp** [comment] 2016-05-09 17:59
lgtm. Tested and working fine.

**Comment by otaviobp** [comment] 2016-05-09 18:00
ops, commented in wrong place

**Comment by brunobottazzini** [comment] 2016-05-09 21:05
Patch merged and issue resolved. Thanks!

**Closed as completed by brunobottazzini** 2016-05-09 21:05 UTC
Labels: bug, cheat-sheet
