### ISSUE TITLE
Cannot run fbp code in browser

### ISSUE THREAD

**Issue by otcyanglei** [solettaproject/soletta-dev-app#81] opened 2016-04-15 02:58 UTC
in web browser, the fbp code cannot be run successfully. The same fbp code can be run with sol-fbp-runner though. 
This seems like the systemd service spawn process failure.

Environment: v1_beta7

System log: 

```
Apr 13 07:37:40 intel-quark systemd[1]: Stopped Run FBP Script when using Solett
a Devapp in web browser.
Apr 13 07:37:40 intel-quark systemd[1]: Created slice system-fbp\x2drunner.slice
.
Apr 13 07:37:40 intel-quark systemd[1]: Started Run FBP Script when using Solett
a Devapp in web browser.
Apr 13 07:37:40 intel-quark systemd[840]: [[0;1;31mfbp-runner@-tmp-test.fbp.serv
ice: Failed at step CHDIR spawning /usr/bin/sol-fbp-runner: Not a directory[[0m
Apr 13 07:37:40 intel-quark systemd[1]: [[0;1;39mfbp-runner@-tmp-test.fbp.servic
e: Main process exited, code=exited, status=200/CHDIR[[0m
Apr 13 07:37:41 intel-quark systemd[1]: [[0;1;39mfbp-runner@-tmp-test.fbp.servic
e: Unit entered failed state.[[0m
Apr 13 07:37:41 intel-quark systemd[1]: [[0;1;39mfbp-runner@-tmp-test.fbp.servic
e: Failed with result 'exit-code'.[[0m
```

**Comment by otcyanglei** [comment] 2016-04-15 03:00
The test.fbp code: 
`_(timer:interval=1000) OUT -> IN _(boolean/toggle:initial_state=true) OUT -> IN _(console)`

**Comment by brunobottazzini** [comment] 2016-04-15 22:03
Fix proposed here: https://github.com/solettaproject/soletta-dev-app/pull/83/commits/793ea641f01f16fbe16b53aa9019764a1228e762

**Comment by brunobottazzini** [comment] 2016-04-18 16:13
@otcyanglei I could run the code here with the new version.

The issue is fixed, I'm closing it 

thanks

**Closed as completed by brunobottazzini** 2016-04-18 16:13 UTC
Labels: bug
